In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a
print(array_a)

[1 2 3]


In [4]:
type(array_a)
array_a.shape

(3,)

Matrix array

In [5]:
array_b = np.array([[1,2,3],[4,5,6]])

In [6]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_b[1]

array([4, 5, 6])

Scalar

In [8]:
array_c = np.array(13)

Arrays vs lists:

In [9]:
list_a = [[1,2,3],[4,5,6]]


In [10]:
len(list_a)

2

In [11]:
array_a = np.array(list_a)

In [12]:
type(array_a), type(list_a)

(numpy.ndarray, list)

In [13]:
print(array_a), print(list_a)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


(None, None)

In [14]:
array_a.shape, len(list_a[0])

((2, 3), 3)

In [15]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [16]:
print(list_b, array_b)

[1, 2, 3, 4, 5, 6] [5 7 9]


In [17]:
import math

array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [18]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# NumPy Fundmentals: 
## Indexing:

In [19]:
array_a = np.array([[1,2,3], [4,5,6]])

## Specific values:

In [20]:
array_a[0], array_a[1], array_a[1,0], array_a[:, 0]

(array([1, 2, 3]), array([4, 5, 6]), 4, array([1, 4]))

## Negative indices:

In [21]:
array_b = np.array([1,2,3])
array_b[-1]

3

## Assigning Values:

In [22]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [23]:
array_a[0] = 2
array_a

array([[2, 2, 2],
       [4, 5, 6]])

In [24]:
list_a = [8,7,8]
array_a[0] = list_a

print(array_a, type(array_a))

[[8 7 8]
 [4 5 6]] <class 'numpy.ndarray'>


In [25]:
array_a [:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [26]:
array_a =  np.array([7,8,9])
array_b = np.array([[1,2,3], [4,5,6]])

In [27]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
list_a = [1,2,3]
list_a + [4]

[1, 2, 3, 4]

In [29]:
array_a + array_b[0]

array([ 8, 10, 12])

In [30]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

## Types of data supported by NumPy

In [31]:
array_a = np.array([[1,2,3],[4,3000,6]], dtype='uint8')
array_a

array([[  1,   2,   3],
       [  4, 184,   6]], dtype=uint8)

In [32]:
array_a = np.array([[1,2,3],[4,3000,6]], dtype='complex64')
array_a = np.array([[1,2,3],[4,3000,0]], dtype='bool')
array_a

array([[ True,  True,  True],
       [ True,  True, False]])

In [33]:
array_a = np.array([[1,2,3],[4,3000,0]], dtype='str')
array_a

array([['1', '2', '3'],
       ['4', '3000', '0']], dtype='<U4')

# Broadcasting:


In [34]:
array_a = np.array([1,2,3])
array_b = np.array([[1], [2]])
matrix_c = np.array([[1,2,3], [4,5,6]])

In [35]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [36]:
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

## Type casting:


In [37]:
np.add(array_b, matrix_c, dtype = 'float64')

array([[2., 3., 4.],
       [6., 7., 8.]])

## Running over an Axis:

In [38]:
np.mean(matrix_c, axis = 0 ), np.mean(matrix_c, axis = 1 )

(array([2.5, 3.5, 4.5]), array([2., 5.]))

In [39]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

# Slicing: 

In [40]:
matrix_A = np.array([[1,2,3], [4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

## Basic Slicing:

In [41]:
matrix_A [3:]

array([], shape=(0, 3), dtype=int32)

## Stepwise slicing:

In [42]:
matrix_b = np.array([[1,1,2,3,1], [1,1,6,3,7], [1,31,4,3,3]])
matrix_b[::2, ::]

array([[ 1,  1,  2,  3,  1],
       [ 1, 31,  4,  3,  3]])

## Conditional slicing

In [43]:
matrix_C = np.array([[1,1,2,3,1], [5,1,6,3,7], [6,31,4,3,3]])
matrix_C[:, 0]

array([1, 5, 6])

In [44]:
matrix_C[:, :]> 2

array([[False, False, False,  True, False],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Multiple conditions

In [45]:
matrix_C[(matrix_C[:, :]> 2) & (matrix_C[:,:] % 2 ==0)]

matrix_C[(matrix_C[:, :]> 2) | (matrix_C[:,:] % 2 ==0)]

array([ 2,  3,  5,  6,  3,  7,  6, 31,  4,  3,  3])

## Dimensions and squeeze function:

In [46]:
matrix_D = np.array([[1,1,2,3,1], [5,1,6,3,7], [6,31,4,3,3]])
matrix_D

array([[ 1,  1,  2,  3,  1],
       [ 5,  1,  6,  3,  7],
       [ 6, 31,  4,  3,  3]])

In [47]:
type(matrix_D[0,0])

numpy.int32

In [48]:
matrix_D[0, :1], matrix_D[0,0], matrix_D[:1,:1]

(array([1]), 1, array([[1]]))

In [49]:
print(matrix_D[:1,:1].squeeze())

1


In [50]:
np.squeeze(matrix_D[:1,:1])

array(1)

In [51]:
matrix_D[:1,:1]

array([[1]])

In [52]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

()
()
()


# Arrays of 0s and 1s:
## Generating data with numpy
### np.empty(), np.zeros(), np.ones(), np.full()


In [53]:
np.empty(shape = (2,4))

array([[0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 7.786e-321, 0.000e+000, 0.000e+000]])

In [54]:
np.zeros(shape = (2,3), dtype= 'int8')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [55]:
np.ones(shape = (2,3), dtype = 'int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [56]:
np.full(shape = (2,3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10]])

## _like functions

In [57]:
matrix_A = np.array([[1,3,4,5,6], [21,3,54132,5326,6], [4124,5,325,36,6]])
matrix_empty_like = np.empty_like(matrix_A)

In [58]:
np.zeros_like(matrix_A)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.arange()

In [59]:
np.arange(  10, dtype='int8')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [60]:
np.arange( 1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Random generators

## Defining Random generators

In [61]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [67]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(loc=2, scale = 3, size=(5,5))

array([[ 1.59077303,  2.28243293,  1.81098674,  5.16174922, -0.06004539],
       [ 0.47233481, -0.3998578 ,  4.19125476,  2.26476316, -4.35327281],
       [ 3.96580322,  0.55714964,  0.34426579,  0.24264015, -0.94773689],
       [ 5.37134498, -1.92952948,  1.85888679,  4.865816  ,  2.78215234],
       [ 1.39928997, -2.50517452, -2.47874891,  4.89605251,  5.560839  ]])

In [75]:
array_RG.normal(loc=20, scale = 5, size=(50,50))

array([[24.06214621, 14.0348754 , 18.12425254, ..., 23.43537336,
        14.90693356, 19.89266042],
       [ 9.4960313 , 25.05017912, 14.21189162, ..., 19.72163188,
        20.81191142, 18.71652209],
       [ 8.54880838, 11.14000758, 18.81960317, ..., 12.21683312,
        27.13563765, 15.33539125],
       ...,
       [19.98348081, 21.79221909, 10.56809376, ..., 25.98232552,
        21.88166283, 26.93275104],
       [24.21697183, 25.58698497, 15.18763551, ..., 22.7442619 ,
        24.68869127, 17.73461285],
       [20.01506103, 26.50584871, 19.34786968, ..., 19.62113836,
        28.98262051, 20.38062053]])

## Generating arrays from know distributions:

In [63]:
array_RG = gen(pcg(seed = 365))
array_RG.poisson(size = (5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]], dtype=int64)

In [64]:
array_RG = gen(pcg(seed = 365))
array_RG.poisson(lam = 10, size = (5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [65]:
# binomial dist 

array_RG = gen(pcg(seed = 365))
array_RG.binomial(n=10, p = 0.4, size = (5,5)).mean()

3.96

In [66]:
# logistic dist 

array_RG = gen(pcg(seed = 365))
array_RG.logistic(loc=2, scale = 0.5, size = (500,500)).max()

7.973136661997539

Application of Random generators 

In [78]:
array_column_1 = array_RG.normal(loc = 2, scale = 3, size=(1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size=(1000))
array_column_3 = array_RG.logistic(loc=11, scale = 3, size = (1000))
array_column_4 = array_RG.exponential(scale = 4, size = (1000))
array_column_5 = array_RG.geometric(p = 0.7,  size = (1000))

In [93]:
random_test_data  = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5]).transpose()
random_test_data

array([[ 1.19142572,  8.7418437 , -2.810037  ,  1.61176816,  1.        ],
       [-1.78721876,  6.61345417,  5.92660855,  0.98157389,  1.        ],
       [-0.0885151 ,  8.10574164, 11.7995461 ,  0.18739931,  1.        ],
       ...,
       [ 3.04527935,  9.63110717,  5.85965622,  4.75565529,  1.        ],
       [ 4.90246549,  9.38293525, 11.05674991,  7.75355448,  1.        ],
       [ 3.30747732,  5.1593447 , 10.4698943 ,  0.10248269,  1.        ]])

In [94]:
np.savetxt('random-test-from-Numpy', random_test_data, fmt = '%s', delimiter=',')

In [95]:
np.genfromtxt('random-test-from-Numpy-', delimiter=',')

array([[ 1.19142572,  8.7418437 , -2.810037  ,  1.61176816,  1.        ],
       [-1.78721876,  6.61345417,  5.92660855,  0.98157389,  1.        ],
       [-0.0885151 ,  8.10574164, 11.7995461 ,  0.18739931,  1.        ],
       ...,
       [ 3.04527935,  9.63110717,  5.85965622,  4.75565529,  1.        ],
       [ 4.90246549,  9.38293525, 11.05674991,  7.75355448,  1.        ],
       [ 3.30747732,  5.1593447 , 10.4698943 ,  0.10248269,  1.        ]])

In [96]:
A = np.array([[1,2,3], [123,412,54], [2415,5,35]])
-np.ones_like(A)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

Importing Data with Numpy

np.loadtxt()  vs np.genfromtxt()

In [115]:
lending_co_data_numeric_1 = np.loadtxt('random-test-from-Numpy-', dtype='float', delimiter=',')
lending_co_data_numeric_1

array([[ 1.19142572,  8.7418437 , -2.810037  ,  1.61176816,  1.        ],
       [-1.78721876,  6.61345417,  5.92660855,  0.98157389,  1.        ],
       [-0.0885151 ,  8.10574164, 11.7995461 ,  0.18739931,  1.        ],
       ...,
       [ 3.04527935,  9.63110717,  5.85965622,  4.75565529,  1.        ],
       [ 4.90246549,  9.38293525, 11.05674991,  7.75355448,  1.        ],
       [ 3.30747732,  5.1593447 , 10.4698943 ,  0.10248269,  1.        ]])

In [116]:
lending_co_data_numeric_2 = np.genfromtxt('random-test-from-Numpy-', dtype='float', delimiter=',')
lending_co_data_numeric_2

array([[ 1.19142572,  8.7418437 , -2.810037  ,  1.61176816,  1.        ],
       [-1.78721876,  6.61345417,  5.92660855,  0.98157389,  1.        ],
       [-0.0885151 ,  8.10574164, 11.7995461 ,  0.18739931,  1.        ],
       ...,
       [ 3.04527935,  9.63110717,  5.85965622,  4.75565529,  1.        ],
       [ 4.90246549,  9.38293525, 11.05674991,  7.75355448,  1.        ],
       [ 3.30747732,  5.1593447 , 10.4698943 ,  0.10248269,  1.        ]])

In [118]:
np.array_equal(lending_co_data_numeric_2 ,  lending_co_data_numeric_1)

True

In [123]:
lending_co_data_numeric_2_nan = np.genfromtxt('lending-co-LT.csv', delimiter=';', dtype = np.str)
lending_co_data_numeric_2_nan

array(['LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice',
       '1,id_1,Product B,Male,Location 2,Region 2,16600.0',
       '2,id_2,Product B,Male,Location 3,,16600.0', ...,
       '1041,id_1041,Product B,Male,Location 23,Region 4,16600.0',
       '1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0',
       '1043,id_1043,Product B,Female,Location 142,Region 6,16600.0'],
      dtype='<U65')

Partial cleaning while importing

In [128]:
ending_co_data_numeric_2_numerical  = np.genfromtxt('Lending-Company-Numeric-Data.csv', delimiter=';', dtype = np.str, skip_header=1)
ending_co_data_numeric_2_numerical

array(['2000,40,365,3061,4171,15041', '1000,40,365,2160,3280,15340',
       '2000,40,365,3041,4241,15321', ..., '2000,40,365,4201,5001,16600',
       '1000,40,365,2080,3320,15600', '2000,40,365,4601,4601,16600'],
      dtype='<U30')

In [129]:
ending_co_data_numeric_2_numerical  = np.genfromtxt('Lending-Company-Numeric-Data.csv', delimiter=';', dtype = np.str, skip_footer=1)
ending_co_data_numeric_2_numerical

array(['2000,40,365,3121,4241,13621', '2000,40,365,3061,4171,15041',
       '1000,40,365,2160,3280,15340', ..., '2000,40,365,4240,5440,16600',
       '2000,40,365,4201,5001,16600', '1000,40,365,2080,3320,15600'],
      dtype='<U30')

In [134]:
ending_co_data_numeric_2_numerical  = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';', dtype = np.str, usecols=(0,2,4))
ending_co_data_numeric_2_numerical

array([['2000', '365', '4241'],
       ['2000', '365', '4171'],
       ['1000', '365', '3280'],
       ...,
       ['', '365', '5001'],
       ['1000', '365', '3320'],
       ['2000', '365', '4601']], dtype='<U5')

In [136]:
lending_co_data_1, lending_co_data_2, lending_co_data_3   = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';', dtype = np.str, usecols=(1,2,3), unpack=True)
lending_co_data_1, lending_co_data_2, lending_co_data_3  

(array(['40', '40', '40', ..., '40', '40', '40'], dtype='<U5'),
 array(['365', '365', '365', ..., '365', '365', '365'], dtype='<U5'),
 array(['3121', '3061', '2160', ..., '4201', '2080', '4601'], dtype='<U5'))

# String vs Object vs Numbers

In [150]:
lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter=', ', dtype = np.object)
print(lending_co_lt)

[b'LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice'
 b'1,id_1,Product B,Male,Location 2,Region 2,16600.0'
 b'2,id_2,Product B,Male,Location 3,,16600.0' ...
 b'1041,id_1041,Product B,Male,Location 23,Region 4,16600.0'
 b'1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0'
 b'1043,id_1043,Product B,Female,Location 142,Region 6,16600.0']


In [153]:
lending_co= np.genfromtxt('lending-Company-Saving.csv', delimiter=', ', dtype = np.str)
print(lending_co)

['LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice'
 '1,id_1,Product B,Male,Location 2,Region 2,16600.0'
 '2,id_2,Product B,Male,Location 3,,16600.0' ...
 '1041,id_1041,Product B,Male,Location 23,Region 4,16600.0'
 '1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0'
 '1043,id_1043,Product B,Female,Location 142,Region 6,16600.0']


In [154]:
# to save file in a faster than csv we use this command
np.save('lending-Company-Saving', lending_co)

In [156]:
lending_data_save = np.load('lending-Company-Saving.npy')
lending_data_save

array(['LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice',
       '1,id_1,Product B,Male,Location 2,Region 2,16600.0',
       '2,id_2,Product B,Male,Location 3,,16600.0', ...,
       '1041,id_1041,Product B,Male,Location 23,Region 4,16600.0',
       '1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0',
       '1043,id_1043,Product B,Female,Location 142,Region 6,16600.0'],
      dtype='<U65')

In [157]:
np.array_equal(lending_data_save, lending_co)

True

## np.savez function

In [159]:
np.savez('lending-Company-Saving', lending_co,lending_data_save )

In [162]:
lending_data_save = np.load('lending-Company-Saving.npz')
lending_data_save['arr_0']

array(['LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice',
       '1,id_1,Product B,Male,Location 2,Region 2,16600.0',
       '2,id_2,Product B,Male,Location 3,,16600.0', ...,
       '1041,id_1041,Product B,Male,Location 23,Region 4,16600.0',
       '1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0',
       '1043,id_1043,Product B,Female,Location 142,Region 6,16600.0'],
      dtype='<U65')

### np.savetxt()

In [163]:
lending_co= np.genfromtxt('lending-Company-Saving.csv', delimiter=', ', dtype = np.str)
print(lending_co)

['LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice'
 '1,id_1,Product B,Male,Location 2,Region 2,16600.0'
 '2,id_2,Product B,Male,Location 3,,16600.0' ...
 '1041,id_1041,Product B,Male,Location 23,Region 4,16600.0'
 '1042,id_1042,Product C,NotSpecified,Location 52,Region 6,15600.0'
 '1043,id_1043,Product B,Female,Location 142,Region 6,16600.0']


In [164]:
np.savetxt('lending-Company-Saving.txt', lending_co, fmt = '%s', delimiter=',')

lending_data_savetxt = np.genfromtxt('lending-Company-Saving.txt', 
                                        delimiter= ',',
                                        dtype= np.str)
                                        

In [166]:
lending_data_savetxt
lending_data_save = np.load('lending-Company-Saving.npy')

np.array_equal(lending_data_savetxt, lending_data_save)

False

In [5]:
!pip install autoviz
from autoviz.AutoViz_Class import AutoViz_Class

# AV = AutoViz_Class()
# df = AV.AutoViz('./data/train.csv', depVar='Survived')

  Using cached autoviz-0.0.85-py3-none-any.whl (46 kB)
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
  Using cached hvplot-0.7.3-py2.py3-none-any.whl (3.1 MB)
  Running setup.py clean for wordcloud
Failed to build wordcloud
    Running setup.py install for wordcloud: started
    Running setup.py install for wordcloud: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\hossa\anaconda3\envs\titanic\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hossa\\AppData\\Local\\Temp\\pip-install-1cor33ai\\wordcloud_b935c7f1b6c84656b5786deb74c1f99c\\setup.py'"'"'; __file__='"'"'C:\\Users\\hossa\\AppData\\Local\\Temp\\pip-install-1cor33ai\\wordcloud_b935c7f1b6c84656b5786deb74c1f99c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\hossa\AppData\Local\Temp\pip-wheel-ynaf08rx'
       cwd: C:\Users\hossa\AppData\Local\Temp\pip-install-1cor33ai\wordcloud_b935c7f1b6c84656b5786deb74c1f99c\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\color_from_image.py -> buil

ModuleNotFoundError: No module named 'autoviz'