In [1]:
import numpy as np

In [3]:
array_a = np.array([1,2,3])

In [6]:
array_a
print(array_a)

[1 2 3]


In [7]:
type(array_a)
array_a.shape

(3,)

Matrix array

In [8]:
array_b = np.array([[1,2,3],[4,5,6]])

In [9]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array_b[1]

array([4, 5, 6])

Scalar

In [11]:
array_c = np.array(13)

Arrays vs lists:

In [12]:
list_a = [[1,2,3],[4,5,6]]


In [13]:
len(list_a)

2

In [14]:
array_a = np.array(list_a)

In [15]:
type(array_a), type(list_a)

(numpy.ndarray, list)

In [16]:
print(array_a), print(list_a)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


(None, None)

In [22]:
array_a.shape, len(list_a[0])

((2, 3), 3)

In [23]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [24]:
print(list_b, array_b)

[1, 2, 3, 4, 5, 6] [5 7 9]


In [27]:
import math

array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [34]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# NumPy Fundmentals: 
## Indexing:

In [35]:
array_a = np.array([[1,2,3], [4,5,6]])

## Specific values:

In [39]:
array_a[0], array_a[1], array_a[1,0], array_a[:, 0]

(array([1, 2, 3]), array([4, 5, 6]), 4, array([1, 4]))

## Negative indices:

In [41]:
array_b = np.array([1,2,3])
array_b[-1]

3

## Assigning Values:

In [44]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [45]:
array_a[0] = 2
array_a

array([[2, 2, 2],
       [4, 5, 6]])

In [47]:
list_a = [8,7,8]
array_a[0] = list_a

print(array_a, type(array_a))

[[8 7 8]
 [4 5 6]] <class 'numpy.ndarray'>


In [49]:
array_a [:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [51]:
array_a =  np.array([7,8,9])
array_b = np.array([[1,2,3], [4,5,6]])

In [52]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [54]:
list_a = [1,2,3]
list_a + [4]

[1, 2, 3, 4]

In [55]:
array_a + array_b[0]

array([ 8, 10, 12])

In [56]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

## Types of data supported by NumPy

In [60]:
array_a = np.array([[1,2,3],[4,3000,6]], dtype='uint8')
array_a

array([[  1,   2,   3],
       [  4, 184,   6]], dtype=uint8)

In [63]:
array_a = np.array([[1,2,3],[4,3000,6]], dtype='complex64')
array_a = np.array([[1,2,3],[4,3000,0]], dtype='bool')
array_a

array([[ True,  True,  True],
       [ True,  True, False]])

In [64]:
array_a = np.array([[1,2,3],[4,3000,0]], dtype='str')
array_a

array([['1', '2', '3'],
       ['4', '3000', '0']], dtype='<U4')

# Broadcasting:


In [68]:
array_a = np.array([1,2,3])
array_b = np.array([[1], [2]])
matrix_c = np.array([[1,2,3], [4,5,6]])

In [69]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [70]:
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

## Type casting:


In [72]:
np.add(array_b, matrix_c, dtype = 'float64')

array([[2., 3., 4.],
       [6., 7., 8.]])

## Running over an Axis:

In [75]:
np.mean(matrix_c, axis = 0 ), np.mean(matrix_c, axis = 1 )

(array([2.5, 3.5, 4.5]), array([2., 5.]))

In [74]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

# Slicing: 

In [77]:
matrix_A = np.array([[1,2,3], [4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

## Basic Slicing:

In [80]:
matrix_A [3:]

array([], shape=(0, 3), dtype=int32)

## Stepwise slicing:

In [88]:
matrix_b = np.array([[1,1,2,3,1], [1,1,6,3,7], [1,31,4,3,3]])
matrix_b[::2, ::]

array([[ 1,  1,  2,  3,  1],
       [ 1, 31,  4,  3,  3]])

## Conditional slicing

In [92]:
matrix_C = np.array([[1,1,2,3,1], [5,1,6,3,7], [6,31,4,3,3]])
matrix_C[:, 0]

array([1, 5, 6])

In [94]:
matrix_C[:, :]> 2

array([[False, False, False,  True, False],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Multiple conditions

In [97]:
matrix_C[(matrix_C[:, :]> 2) & (matrix_C[:,:] % 2 ==0)]

matrix_C[(matrix_C[:, :]> 2) | (matrix_C[:,:] % 2 ==0)]

array([ 2,  3,  5,  6,  3,  7,  6, 31,  4,  3,  3])

## Dimensions and squeeze function:

In [98]:
matrix_D = np.array([[1,1,2,3,1], [5,1,6,3,7], [6,31,4,3,3]])
matrix_D

array([[ 1,  1,  2,  3,  1],
       [ 5,  1,  6,  3,  7],
       [ 6, 31,  4,  3,  3]])

In [101]:
type(matrix_D[0,0])

numpy.int32

In [105]:
matrix_D[0, :1], matrix_D[0,0], matrix_D[:1,:1]

(array([1]), 1, array([[1]]))

In [110]:
print(matrix_D[:1,:1].squeeze())

1


In [113]:
np.squeeze(matrix_D[:1,:1])

array(1)

In [114]:
matrix_D[:1,:1]

array([[1]])

In [115]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

()
()
()


# Arrays of 0s and 1s:
## Generating data with numpy
### np.empty(), np.zeros(), np.ones(), np.full()


In [150]:
np.empty(shape = (2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.05927674e-320, 9.34609110e-307,
        8.34420522e-308]])

In [151]:
np.zeros(shape = (2,3), dtype= 'int8')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [153]:
np.ones(shape = (2,3), dtype = 'int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [154]:
np.full(shape = (2,3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10]])

## _like functions

In [158]:
matrix_A = np.array([[1,3,4,5,6], [21,3,54132,5326,6], [4124,5,325,36,6]])
matrix_empty_like = np.empty_like(matrix_A)

In [176]:
np.zeros_like(matrix_A)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.arange()

In [180]:
np.arange(  10, dtype='int8')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [182]:
np.arange( 1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## Random generators

## Defining Random generators

In [183]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [189]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

## Generating arrays from know distributions: