## Importing the Packages

In [583]:
import numpy as np

In [584]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

## Importing the Data

In [585]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header = 1, autostrip = True)
raw_data_np
np.loadtxt

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [586]:
np.isnan(raw_data_np).sum()

88005

In [587]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)
temporary_mean

<ipython-input-587-f19a776f48b3>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [588]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [589]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                           temporary_mean,
                           np.nanmax(raw_data_np, axis = 0)])
temporary_stats

<ipython-input-589-022d84781d86>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
<ipython-input-589-022d84781d86>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [590]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [591]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [592]:
loan_data_strings = np.genfromtxt("loan-data.csv",
                                  delimiter = ';',
                                  skip_header = 1,
                                  autostrip = True, 
                                  usecols = columns_strings,
                                  dtype = np.str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### The Names of the Columns

In [594]:
header_full = np.genfromtxt("loan-data.csv",
                            delimiter = ';',
                            autostrip = True,
                            skip_footer = raw_data_np.shape[0],
                            dtype = np.str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [595]:
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

In [596]:
header_strings, header_numeric

(array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'))

## Creating Checkpoints:

In [597]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [598]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [599]:
checkpoint_test['header'], checkpoint_test['data']

(array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 array([['May-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
        ['', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
        ['Sep-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
        ...,
        ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
        ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
        ['Dec-15', 'Current', '36 months', ..., '',
         'https://www.lendingclub.com/brows

In [600]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

## Manipulating String Columns

In [601]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [602]:
header_strings[0] = 'issue_date'

In [603]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [604]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [605]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], '-15')

In [606]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
months[1]

'Jan'

In [607]:
for i in range(13):
        loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                          i,
                                          loan_data_strings[:,0])

In [608]:
np.unique(loan_data_strings[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [609]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [610]:
# charged off, Default, ' ', late(31-120)  are considered as risky while 'current, fully paid, in grace period, issued, late(16-30)' as good signs
np.unique(loan_data_strings[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [611]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])
status_good = np.array(['Current', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)'])

In [612]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),
                                          0,
                                          loan_data_strings[:,1])
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_good),
                                          1,
                                          loan_data_strings[:,1])

# loan_data_strings = np.where(np.isin(loan_data_strings[:,1],status_bad), 0, 1)

In [613]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [614]:
np.unique(loan_data_strings[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [615]:
loan_data_strings[:, 2] = np.chararray.strip(loan_data_strings[:,2], 'months')

In [616]:
# in CRM we always assume the worse for missing values
loan_data_strings[:,2] = np.where(loan_data_strings[:,2]=='', '36 ', loan_data_strings[:, 2])

### Grade and Subgrade

In [617]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [618]:
np.unique(loan_data_strings[:,3]), np.unique(loan_data_strings[:,4]), 

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'))

#### Filling Sub Grade

In [619]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    print(i)
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

A
B
C
D
E
F
G


In [620]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [621]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == ''),
                                      'H1',
                                      loan_data_strings[:,4])

In [622]:
np.unique(loan_data_strings[:,3], return_counts=True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

#### Removing Grade

In [623]:
loan_data_strings = np.delete(loan_data_strings, 3 , axis=1)

In [624]:
header_strings = np.delete(header_strings , 3)

#### Converting Sub Grade

In [625]:
np.unique(loan_data_strings[:, 3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [626]:
keys = list(np.unique(loan_data_strings[:,3]))                         
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [627]:
for i in np.unique(loan_data_strings[:,3]):
        loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_strings[:,3])

In [628]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [629]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [630]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4]=='')|(loan_data_strings[:,4]=='Not Verified'), 0, 1 )

In [631]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [632]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [633]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [634]:
# we find that the numbers here are same as the id numbers column
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [635]:
np.array_equal(loan_data_strings[:, 5].astype('int32'), loan_data_numeric[:,0].astype('int32'))

True

In [636]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)


In [637]:
header_strings = np.delete(header_strings, 5)

In [638]:
header_strings[5], loan_data_strings[:,5]

('addr_state', array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69'))

In [639]:
header_numeric, loan_data_numeric[:,0]

(array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'),
 array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.]))

### State Address

In [640]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [641]:
header_strings[5], np.unique(loan_data_strings[:, 5], return_counts=True)

('addr_state',
 (array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
         'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
         'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
         'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
  array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
           84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
          341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
           17,  216,  148,   49,   27], dtype=int64)))

In [642]:
# we find that the empty state is bench mark as when you have many variables you always need a bench mark dummy variable 
# 
np.unique(loan_data_strings[:, 5]).size

50

In [643]:
states_names, states_count = np.unique(loan_data_strings[:, 5], return_counts=True)

states_count_sorted = np.argsort(-states_count)

states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [644]:
#  WE have very little data for so many states to examine each one individually.
#  The more categories a variable has, the fewer data will be available for each one.
# If we assign a unique value to each state, this will allow outliers to have a big influence on the coefficients. 
# There are more applications with missing or unreported addresses than there are for 45 of the other states.
# best solution is to group the states according to their geographical locations.
# first we assign the NAN value to a zero value

loan_data_strings[:, 5] = np.where(loan_data_strings[:,5] == '', 0, loan_data_strings[:,5])


In [645]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [646]:
loan_data_strings[:,5 ] = np.where(np.isin(loan_data_strings[:,5] , states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5 ] = np.where(np.isin(loan_data_strings[:,5] , states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5 ] = np.where(np.isin(loan_data_strings[:,5] , states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5 ] = np.where(np.isin(loan_data_strings[:,5] , states_east), 4, loan_data_strings[:,5])

In [647]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [648]:
loan_data_strings

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [649]:
loan_data_strings = loan_data_strings.astype('int')
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [650]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

    

In [651]:
checkpoint_strings = checkpoint('checkpoint_strings', header_strings, loan_data_strings)

In [652]:
checkpoint_strings['header'], checkpoint_strings['data']

(array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
       dtype='<U19'),
 array([[ 5,  1, 36, 13,  1,  1],
        [ 0,  1, 36,  5,  1,  4],
        [ 9,  1, 36, 10,  1,  4],
        ...,
        [ 6,  1, 36,  5,  1,  1],
        [ 4,  1, 36, 17,  1,  3],
        [12,  1, 36,  4,  0,  3]]))

## Manipulating Numeric Columns

In [653]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [654]:
np.isnan(loan_data_numeric).sum()

0

### Substitute "Filler" Values

In [655]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [656]:
temporary_fill, temporary_mean

(68616520.0,
 array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85]))

In [657]:
np.isin(loan_data_numeric[:,1], temporary_fill).sum()

500

#### Temporary Stats

In [658]:
# first row are minimum values, second row are mean values, third row are maximum values
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [659]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [660]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [661]:
temporary_stats[0, columns_numeric[3]]

6.0

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [662]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [663]:
for i in [1,3,4,5]:
    print(i)
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, 
                                    temporary_stats[2, columns_numeric[i]],
                                    loan_data_numeric[:,i])
    

1
3
4
5


In [664]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [665]:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter=',', autostrip=True, skip_header = 1, usecols = 3)
EUR_USD

# in analysis we often use the adjusting closing price


array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [666]:
loan_data_strings[:, 0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [667]:
exchange_rate = loan_data_strings[:, 0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate) 

exchange_rate = np.where(exchange_rate == 0,
                             np.mean(EUR_USD),
                             exchange_rate)    


In [668]:
exchange_rate.shape, loan_data_numeric.shape

((10000,), (10000, 6))

In [669]:
exchange_rate= np.reshape(exchange_rate , (10000,1))

In [670]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [671]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [672]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [673]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [674]:
columns_dollar = np.array([1,2,4,5])

In [675]:
loan_data_numeric[:, 6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [811]:
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))



ValueError: cannot reshape array of size 200 into shape (10000,1)

In [677]:
loan_data_numeric, loan_data_numeric.shape

(array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
        [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
        [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
        [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
        [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]]),
 (10000, 11))

#### Expanding the header

In [678]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [679]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [680]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [681]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [682]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [683]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [684]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [685]:
header_numeric = header_numeric[columns_index_order]

In [686]:
loan_data_numeric = loan_data_numeric[:, columns_index_order]

### Interest Rate

In [687]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [693]:

loan_data_numeric[:,5]/100

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [695]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [696]:
checkpoint_numeric = checkpoint('checkpoint_numeric', header_numeric, loan_data_numeric)


In [697]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [702]:
checkpoint_strings['data'].shape, checkpoint_numeric['data'].shape, checkpoint_strings['header'].shape, checkpoint_numeric['header'].shape

((10000, 6), (10000, 11), (6,), (11,))

In [717]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [ ]:
loan_data

In [709]:
np.isnan(loan_data).sum()

0

In [711]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

## Sorting the New Dataset

In [718]:
loan_data= loan_data[np.argsort(loan_data[:,0])]


In [719]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

## Storing the New Dataset

In [721]:
loan_data = np.vstack((header_full, loan_data))

In [723]:
np.savetxt('loan_data_preprocessed.csv', loan_data, fmt = '%s', delimiter = ',')

In [729]:
np.sort(loan_data)

array([['addr_state', 'exchange_rate', 'funded_amnt_EUR', ..., 'total_pymnt_EUR',
        'total_pymnt_USD', 'verification_status'],
       ['0.0', '0.1825', '1.0', ..., '908.3500315917876', '974.4960808923015', '9950.0'],
       ['0.20989999999999998', '1.0', '1.0', ..., '60.0', '871.788942820218', '959.75'],
       ...,
       ['0.0', '0.0', '0.2899', ..., '5600.0', '68614880.0', '8.0'],
       ['0.0', '0.0', '0.2899', ..., '4000.0', '4000.0', '68615915.0'],
       ['0.0', '0.0', '0.0', ..., '609.8876553299532', '666.85', '68616519.0']], dtype='<U32')

In [726]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [732]:
s = np.array([[2,1,3], [-2,2,1]])

In [740]:
-np.sort(s,axis=1)

array([[-1, -2, -3],
       [ 2, -1, -2]])

In [747]:
np.mean(loan_data, axis=1)

TypeError: cannot perform reduce with flexible type